spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:silvercircledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true

# Security
jwt.secret=7d84814dfd41db61e6878b30e8c45d3e09849206ea194f42fdfeb2b13edef8c7
jwt.expiration=86400000

# Server port
server.port=8080
